{% set name = "hupper" %}
{% set version = "1.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5869ec2a46ba8ad481b0a27ca68f3e01dc7d3424925b7c872d9fcdff44b43442

build:
  noarch: python
  number: 0
  entry_points:
    - hupper = hupper.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - hupper
  commands:
    - hupper --help

about:
  home: https://github.com/Pylons/hupper
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Integrated process monitor for developing and reloading daemons.
  doc_url: https://docs.pylonsproject.org/projects/hupper/
  dev_url: https://github.com/Pylons/hupper

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
