travis:
  secure:
    BINSTAR_TOKEN: l//TeKM24VvIPAYpd7PblDTbAhrKwkbY/hoW5arr3MHWbFtIKWivIf8whAnS2KRFycvbLAQyk3BN5d3JXkcHgg9e+P52IEttCY7xR66Xo3plpX8V1D50lceimNHbaq5ORyQ8/bKKXq+Xb1r6EHZ8CR2n7Npp0EXkY2Yo/EqlV6tOCkPglisLF0Qo8Zh/D7yfe8Q3X9MqCEN5bWtACC6MSaSEDMPfMBP2EsRtsdFW4ILUXYgZtUy7BS07c1gAViPxPergLVtYxB9o3mxNxNwPkHEWs0PtBQmK/0Apqrtkfx3U0yokFFGyVvUDNkcs7LJM/ftupQH+o1W2MjMwhMBx1IrBRifK44shUbxAJmCKlcwhLigixvDObr6kN4474zfChASyHckoM17PutvX+LD/FTPZwXiFMlivvf/hELjHEIIYhfNyfGOkLTp5Gb0HtND86Pyatp4Z5nBA97JP5EUt3TxVFJYlIR8EYq3CGG5+gf+WwArXvi+dvugzILGmsIQcdd4N55Xjm83RXa1Zt7ENnq2oIzeLNqtOqV1XvRXdw+A/TzJK+MDZaNo2P9IEjRlx7s0av4InnCJ5kuh0ZWtbJUk95Q8R3/gU6AzYULUs7cy2PF/4xaAqXCuzChZy6QaA4UrGWk15E53BxNT2zZp3j0iV8EKCHUfDkt1Pb4Dom6k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
